### ISSUE TITLE
Provide support for ctrl+space grab'n'move style

### ISSUE THREAD

**Issue by maboiteaspam** [rstgroup/fabricjs-viewport#16]
Hi,

I had to spend sometime to figure out how to make ctrl+space grabbing possible and nicely behaved.

I thought it might worth to be shared.

Workspace is a class with a scene property of type fabric.CanvasWithViewport.
Then we d have those two methods to enable / disable the new behavior.

Note the fabric.fastCanvas. 
Which is not standard, but required. 
It provides supports for requestAnimationFrame, which is good.

```js
var Workspace = (function(){
// see below
  var fastCanvas = fabric.fastCanvas(fabric.CanvasWithViewport);
  function Workspace(el){
    this.el = $(el);
    this.scene = new fastCanvas(el);
  }
  var mouseDown = false;
  var spacePressed = false;
  var lastEv;
  Workspace.prototype.enableGrabbing = function(){
    var that = this;
    $(document)
      .on('mousemove.spaceGrab', function(ev){
        lastEv = ev;
      })
      .on('mousedown.spaceGrab', function(ev){
        mouseDown = true;
      })
      .on('mouseup.spaceGrab', function(ev){
        mouseDown = false;
      })
      .on('keydown.spaceGrab', _.throttle(function(ev){
        if(!spacePressed){
          spacePressed = ev.keyCode===32 && mouseDown;
          if(spacePressed){
            that.scene.selection =!spacePressed;
            that.scene.isGrabMode = spacePressed;
            that.scene.setCursor('grabbing');
            that.scene.__onMouseUp(lastEv);
            that.scene._onMouseDownInGrabMode(lastEv);
            that.scene.renderTop();
          }
        }
        if(spacePressed) ev.preventDefault();
      },5))
      .on('keyup.spaceGrab', _.throttle(function(){
        if(spacePressed){
          spacePressed = false;
          that.scene.setCursor('auto');
          that.scene.isGrabMode = spacePressed;
          that.scene.selection = !spacePressed;
          that.scene.__onMouseUp(lastEv);
          that.scene._onMouseUpInGrabMode(lastEv);
        }
      },5));
  };
  Workspace.prototype.disableGrabbing = function(){
    $(document)
      .off('mousemove.spaceGrab')
      .off('mousedown.spaceGrab')
      .off('mouseup.spaceGrab')
      .off('keydown.spaceGrab')
      .off('keyup.spaceGrab');
  };

  return Workspace;
})();
```

for completness
```js
fabric.fastCanvas = function(_super){
  var __hasProp = {}.hasOwnProperty;
  var __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };
  return (function(_super) {
    __extends(fastCanvas, _super);
    function fastCanvas() {
      this.frame;
      fastCanvas.__super__.constructor.apply(this, arguments);
    }
    fastCanvas.prototype.renderAll = function() {
      var args = arguments;
      var that = this;
      window.cancelAnimationFrame(this.frame);
      this.frame = window.requestAnimationFrame(function(){
        fastCanvas.__super__.renderAll.apply(that, args);
      });
    };
    return fastCanvas;
  })(_super || fabric.Canvas);
};
```

Hope it works nicely for others  too ^^ i can test only firefox here..

**Comment by Kampii** [comment]
Hi,

I am hoping that you could shed some light in my problem. So here (http://c-ev.com/zoom/v4.1/example/index.html) is the test page that is based on the fabricjs-vieport code. This (http://c-ev.com/zoom/v4.1/dist/fabricjs_viewport.js) is the javascript that is being used. The zoom in and out button has been replaced with mouse wheel zoom and the grab button has been replaced with the "shift + left mouse click" to drag the area. This code has multiple problems, but the main ones are:
1. The zoom center should be the coordinate of the mouse cursor. It works only if the image is not dragged.
2. The drag mode works correctly only when the image is not zoomed in. When image is zoomed in, then the grab point does not stick with the mouse.

Do you have some test page where I could see how your ctrl+space drag works and whether it affects the zoom center? If not, do you have any clue how to fix these main 2 issues?

I would highly appreciate any guidelines.

**Comment by maboiteaspam** [comment]
I was not able to help you at that time, sorry.

**Comment by Kampii** [comment]
Hi it is alright! Do you have any guidelines?

**Comment by maboiteaspam** [comment]
there you go 
http://maboiteaspam.github.io/fabircjs-viewport-grabnmove/demo.html
https://github.com/maboiteaspam/fabircjs-viewport-grabnmove

you can test, try, checkout, pr as you like.

**Comment by Kampii** [comment]
Thanks.. but the zoomcenter doesn't really work. I'll post a solution if I find one.
