### ISSUE TITLE
Zooming out and setting zoom level positions objects incorrectly. Origin problems?  

### ISSUE THREAD

**Issue by cmawhorter** [rstgroup/fabricjs-viewport#2]
I like your implementation and this is good enough for my needs.  Thanks.

However, I think there is a problem with the point being zoomed in/out of.   You can see it by zooming in and out repeatedly.  The rectangle should always return to it's original position when you hit zoom level 1.0, but this is not the case.

Couple examples:

1. Zoom out until rectangle is very small. (I hit zoom out 20x)
2. Zoom in. Rectangle position in the viewport will move toward lower right as you zoom.

And:

Doing `c.setZoom(.3);` will lead to the rectangle disappearing off screen.

**Comment by cmawhorter** [comment]
> change viewport position before zooming

change viewport position via panning?

**Comment by wojtek-krysiak** [comment]
Problem is when you change viewport position (via panning) and then start to zoom.

**Comment by cmawhorter** [comment]
i must've been aware of this because I disabled user panning in our production product for some reason. i'll take a look, hmm....

**Comment by wojtek-krysiak** [comment]
@disjunction fix resolves it
