### ISSUE TITLE
Zoom out and Zoom Back in - Position not the same (Fixed! Demo uses pre-bugfix version)

### ISSUE THREAD

**Issue by tamusjroyce** [rstgroup/fabricjs-viewport#24]
In the example, http://rstgroup.github.io/fabricjs-viewport/, when you zoom out then zoom back, the items are no longer in the same position. Is this on purpose? Is it reproducible? or is it a bug?

Google Chrome - Version 43.0.2357.81 m

**Comment by disjunction** [comment]
Seems to be related to this issue #2, which has already been solved.
The example just still refers to the older version.

**Comment by TamusJRoyce** [comment]
Sweet. Sorry I missed that. Thanks for the quick answer. I'll update the people so they know. Not reproducible on the latest version. Thanks!
